#!/usr/bin/env python
dna2rna={        ' DT':'  U',
    ' DA':'  A', ' DU':'  U', ' DC':'  C', ' DG':'  G', ' DI':'  A',
    '  A':'  A', '  U':'  U', '  C':'  C', '  G':'  G', '  I':'  A',
}

modres2na = {    ' DT':' DT',
    ' DA':' DA', ' DU':' DU', ' DC':' DC', ' DG':' DG', ' DI':' DI',
    '  A':'  A', '  U':'  U', '  C':'  C', '  G':'  G', '  I':'  I',
    '2PR':' DG', 'MA6':'  A', 'MIA':'  A', 'SRA':'  A', 'AP7':' DA',
    'PSU':'  U', 'CCC':'  C', '12A':'  A', 'S4C':'  C', 'UR3':'  U',
    'RIA':'  A', 'GDP':'  G', 'PPU':'  A', '2SG':'  G', 'BGM':' DG',
    '6MZ':'  A', 'A7E':'  A', '7AT':'  A', 'UBD':'  U', 'PYO':'  U',
    'M5M':'  C', '4OC':'  C', 'AET':'  A', 'U37':'  U', '2AU':'  U',
    'U33':' DU', 'G46':'  G', '1MA':'  A', '1MG':'  G', 'G7M':'  G',
    '10C':'  C', 'MNU':'  U', ' YG':'  G', '8AN':'  A', 'M2G':'  G',
    '7MG':'  G', 'AF2':' DA', 'CSL':' DC', 'GRB':'  G', '5FU':'  U',
    '5MU':'  U', 'SSU':'  U', '70U':'  U', 'A5M':'  C', ' IU':'  U',
    'CBR':' DC', 'LCG':' DG', 'CBV':'  C', '5MC':'  C', 'LCA':'  A',
    ' IC':'  C', 'ANZ':'  A', ' IG':'  G', 'U8U':'  U', 'UMS':' DU',
    'DOC':' DC', '1RN':'  U', '5CG':' DG', 'XUG':' DG', 'SUR':'  U',
    'A2M':'  A', 'UD5':'  U', '1SC':'  C', '6IA':'  A', 'FMU':'  U',
    'GTP':'  G', '3DA':' DA', 'CG1':'  G', 'GMP':'  G', 'N5M':'  C',
    'OMC':'  C', ' CH':'  C', 'A23':'  A', 'OMG':'  G', 'H2U':'  U',
    'BRU':' DU', 'N79':'  A', 'YYG':'  G', 'U34':'  U', 'OMU':'  U',
    'RUS':'  U', '4SU':'  U', 'UFT':' DU', 'QUO':'  G', 'GDO':'  G',
    '5IC':'  C', '2MU':'  U', 'GF2':' DG', '5AA':' DA', '2MA':'  A',
    '2MG':'  G', 'FHU':'  U', 'T6A':'  A', 'ONE':'  U', 'G3A':'  G',
    'RPC':'  C', 'PGP':'  G', 'UCL':' DU', 'UZR':'  U', '5BU':'  U',
    'MTU':'  A', 'P5P':'  A', 'N6G':'  G', 'CFL':' DC', '23G':'  G',
    'US5':'  U', 'CFZ':' DC', 'A9Z':'  A', 'AVC':'  A', 'RSQ':'  U',
}
